### ISSUE TITLE
11.6 todo 2

### ISSUE THREAD

**Issue by zdolny** [nescomtm/zad_116#2]
- [x] blad w konsoli mowi o metodzie `removeCard` - porownaj gdzie ja definiujesz z inna tego typu metoda `removeColumn`
- [x] ostyluj aplikacje

**Comment by nescomtm** [comment]
błąd odnosił się do removeCard ale chodziło o card.prototype było definiowane w funkcji card a powinno poza nią,

a ostylowanie to takie skromne zrobiłem bo bardzo nie wiem jak to ładnie ułożyć bo nie znam zasad kanban

**Comment by zdolny** [comment]
super, ze blad ogarniety
- [x] jesli chodzi o stylowanie to prosze, aby to wygladalo jak tablica kanban, tutaj zrodlo na temat kanbana: https://www.atlassian.com/agile/kanban Nie musi to byc wielkie stylowanie, ale zeby wygladalo przynajmniej tak: https://scr.hu/ANe1Wo
- [x] obecnie nie moge przeciagnac karty na inna kolumne, w ktorej nie ma innych kart
- [x] plik `script (1).js` do usuniecia
- [x] masz zablakana niepotrzebna deklaracje `function addCard(){ ... `
- [x] zmien nazwe konstruktora z `card` na `Card` - to jest dobra praktyka, aby funkcje konstruujace nazywac z wielkiej litery aby odroznic je od zwyklych funkcji
- [x] popraw prosze wciecia w js aby kod byl bardziej czytelny

**Comment by nescomtm** [comment]
wysyłam wersje robocza

**Comment by zdolny** [comment]
te punkty, ktore zaznaczyles sa ok, czekam zatem na pozostale i zauwazylem jeszcze jedna rzecz:
- [x] masz "chwytanie" elementow, z ktorymi nic nie robisz wiec do usuniecia. W dwoch miejscach np `$('#board .column-container');`

**Comment by nescomtm** [comment]
proszę o ostateczne sprawdzenie zadania

**Comment by zdolny** [comment]
w css:
- [x] w `card` brakuje Ci kropki
- [x] nie ma czegos takiego jak `font-style: bold;`
w js:
- [x] linie 111 i 113 sa niepotrzebne

**Comment by nescomtm** [comment]
font-weight powinno byc i juz jest
